title: Ketaki Ghatole
description: Building at the intersection of AI & Biology
url: "https://98ketaki.github.io"
baseurl: ""

exclude:
  - "*.pdf"
  - "ketaki-homepage-mockup.html"
  - README.md
  - Gemfile
  - Gemfile.lock
